rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
env:
  DATABASE_URL:
    adapter: sqlite3
    database: ":memory:"
    timeout: 500
notifications:
  irc: "irc.freenode.org#lokka"
  irc: "irc.freenode.org#lokka-ja"
